"""add_content_creator_role_and_tables

Revision ID: 36ded632c2f5
Revises: 384af1400370
Create Date: 2026-05-01 02:45:55.218234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '36ded632c2f5'
down_revision: Union[str, None] = '384af1400370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tables content_creators, portfolio_items, booking_requests, cc_engagements
    # were already created by SQLAlchemy create_all() on app startup.
    # creative_strategists/campaign_ideas/creative_engagements never existed in this DB.
    # SQLite does not support ALTER COLUMN — role type change is a no-op at the DB level.
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('MERCHANT', 'INFLUENCER', 'ADMIN', 'CONTENT_CREATOR', name='userrole'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.alter_column('campaigns', 'cc_engagement_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('creative_strategists',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_name_ar', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('bio_ar', sa.TEXT(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('specializations', sqlite.JSON(), nullable=False),
    sa.Column('languages', sqlite.JSON(), nullable=False),
    sa.Column('consultation_rate_jod', sa.FLOAT(), nullable=False),
    sa.Column('completed_engagements', sa.INTEGER(), nullable=False),
    sa.Column('milestone_count', sa.INTEGER(), nullable=False),
    sa.Column('total_earned_jod', sa.FLOAT(), nullable=False),
    sa.Column('avg_rating', sa.FLOAT(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('embedding_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creative_strategists_user_id', 'creative_strategists', ['user_id'], unique=1)
    op.create_table('creative_engagements',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('campaign_idea_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creative_strategist_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('agreed_fee_jod', sa.FLOAT(), nullable=False),
    sa.Column('merchant_notes', sa.TEXT(), nullable=True),
    sa.Column('strategist_notes', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_idea_id'], ['campaign_ideas.id'], ),
    sa.ForeignKeyConstraint(['creative_strategist_id'], ['creative_strategists.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_ideas',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creative_strategist_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title_ar', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('description_ar', sa.TEXT(), nullable=True),
    sa.Column('target_audience', sa.TEXT(), nullable=True),
    sa.Column('suggested_platforms', sqlite.JSON(), nullable=False),
    sa.Column('content_format', sqlite.JSON(), nullable=False),
    sa.Column('influencer_type', sa.TEXT(), nullable=True),
    sa.Column('business_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estimated_budget_jod', sa.FLOAT(), nullable=True),
    sa.Column('timeline_days', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('view_count', sa.INTEGER(), nullable=False),
    sa.Column('adoption_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creative_strategist_id'], ['creative_strategists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_ideas_creative_strategist_id', 'campaign_ideas', ['creative_strategist_id'], unique=False)
    # ### end Alembic commands ###
