"""initial_schema

Revision ID: 3c4ba0287ac3
Revises: 
Create Date: 2026-04-18 22:54:23.944347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4ba0287ac3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('amount_jod', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RELEASED', 'DISPUTED', name='milestonestatus'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_milestones_id'), 'campaign_milestones', ['id'], unique=False)
    op.create_table('campaign_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_reports_id'), 'campaign_reports', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('agreed_rate_jod', sa.Float(), nullable=False),
    sa.Column('brief', sa.String(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CONTENT_SUBMITTED', 'CONTENT_APPROVED', 'RELEASED', 'DISPUTED', 'CANCELLED', name='bookingstatus'), nullable=True),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('content_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('content_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ai_review_result', sa.JSON(), nullable=True),
    sa.Column('escrow_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_transactions.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_booking_id'), 'messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('influencers', sa.Column('audience_gender_split', sa.JSON(), nullable=True))
    op.add_column('influencers', sa.Column('audience_age_split', sa.JSON(), nullable=True))
    op.add_column('influencers', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('influencers', sa.Column('available_until', sa.DateTime(), nullable=True))
    op.add_column('influencers', sa.Column('stripe_connect_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'stripe_connect_account_id')
    op.drop_column('influencers', 'available_until')
    op.drop_column('influencers', 'available_from')
    op.drop_column('influencers', 'audience_age_split')
    op.drop_column('influencers', 'audience_gender_split')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_booking_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_campaign_reports_id'), table_name='campaign_reports')
    op.drop_table('campaign_reports')
    op.drop_index(op.f('ix_campaign_milestones_id'), table_name='campaign_milestones')
    op.drop_table('campaign_milestones')
    # ### end Alembic commands ###
