"""add_content_quality_score

Revision ID: a88c5d38d405
Revises: 3c4ba0287ac3
Create Date: 2026-04-18 23:28:39.706752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88c5d38d405'
down_revision: Union[str, None] = '3c4ba0287ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('content_quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'content_quality_score')
    # ### end Alembic commands ###
